console.log("hello my dream")
console.log("ngong")
console.log("chiken diner")
console.log("leaning web dev")
console.log("chiken diner")
console.log("leaning web dev")
console.log("hello my dream")
console.log("ngong")
console.log("chiken diner")
console.log("leaning web dev")
console.log("hello my dream")
console.log("ngong")
